name: run api testing
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    api-test:
        strategy:
            matrix:
                node-version: [18.x,19.x,20.x]
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{matrix.os}}
                
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm install

            - name: build
              run: npm run build

            - name: API testing
              run: npm test

            - uses: actions/upload-artifact@v3
              with:
                name: build
                path: ./build
